# Generated by Django 5.2.5 on 2025-08-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_subject_five_star_subject_one_star_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='five_star',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='one_star',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='three_star',
        ),
    ]
