# Generated by Django 5.2.5 on 2025-08-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_remove_teacher_subject_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='five_star',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='one_star',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='three_star',
        ),
    ]
