# Generated by Django 5.2.5 on 2025-08-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_remove_subject_five_star_remove_subject_one_star_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='five_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='one_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='three_star',
            field=models.IntegerField(default=0),
        ),
    ]
