# Generated by Django 5.2.5 on 2025-08-19 12:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50)),
                ('phase', models.CharField(max_length=50)),
                ('total_students', models.PositiveIntegerField()),
                ('total_responsive', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('five_star', models.PositiveIntegerField()),
                ('three_star', models.PositiveIntegerField()),
                ('one_star', models.PositiveIntegerField()),
                ('average_percentage', models.FloatField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.batch')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.batch')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.teacher')),
            ],
        ),
    ]
