# Generated by Django 5.2.5 on 2025-08-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_subject_five_star_subject_one_star_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
