# Generated by Django 5.2.5 on 2025-08-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='five_star',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='one_star',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='three_star',
        ),
    ]
