# Generated by Django 5.2.5 on 2025-08-20 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_remove_subject_five_star_remove_subject_one_star_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='performance',
            name='average_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='performance',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedback.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='five_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='one_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='three_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='batch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='total_responsive',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='total_students',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='average_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.batch'),
        ),
    ]
